export const PREFIX = '@ENM-'

const AsyncStorageEnum = {
	DISPLAYED_INTRO: `${PREFIX}DISPLAYED_INTRO`,
	MESSAGE_CODE: `${PREFIX}MESSAGE_CODE`,
	USER: `${PREFIX}USER`,
	LEMBRAR_DADOS_ACESSO: `${PREFIX}LEMBRARDADOSACESSO`,
	FB_ACCESS_TOKEN: `${PREFIX}FBACCESSTOKEN`,

	ACCESS_TOKEN: `${PREFIX}ACCESSTOKEN`,
	REFRESH_TOKEN: `${PREFIX}REFRESHTOKEN`,
	EXPIRES_AT: `${PREFIX}EXPIRESAT`,
	REFRESH_EXPIRES_AT: `${PREFIX}REFRESHEXPIRESAT`,
	AUTHORITIES: `${PREFIX}AUTHORITIES`,

	EMPLOYEE_ID: `${PREFIX}EMPLOYEID`,
	NEXT_STEPS: `${PREFIX}NEXTSTEPS`,

	RESTAURANT: `${PREFIX}RESTAURANT`,
	RESTAURANT_ID: `${PREFIX}RESTAURANTID`,
	RESTAURANT_SIGNUP: `${PREFIX}RESTAURANTSIGNUP`,

	CLIENT_UUID: `${PREFIX}CLIENTUUID`,
	REGISTER: `${PREFIX}REGISTER`,
	PUBLIC_KEY: `${PREFIX}PUBLICKEY`,
	PRIVATE_KEY: `${PREFIX}PRIVATEKEY`,
	SERVER_PUBLIC_KEY: `${PREFIX}SERVERPUBLICKEY`,
	SIGN_UP_FORM: `SIGN_UP_FORM`
}
export default AsyncStorageEnum
